<?php

namespace AppBundle\Repository;

/**
 * DeclarationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclarationRepository extends \Doctrine\ORM\EntityRepository
{
}
