<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUpcoming(){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('e')
            ->from('AppBundle:Event', 'e')
            ->where('e.date >= :now')
            ->setParameters(array('now' => new \DateTime()));

        return $qb->getQuery()->getResult();
    }
}
